/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(aruco_detector.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(269a237ea4b83983a1a491c2dc348c02)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/medusa/aruco_detector.h>
// pydoc.h is automatically generated in the build directory
#include <aruco_detector_pydoc.h>

void bind_aruco_detector(py::module& m)
{

    using aruco_detector = ::gr::medusa::aruco_detector;


    py::class_<aruco_detector,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<aruco_detector>>(m, "aruco_detector", D(aruco_detector))

        .def(py::init(&aruco_detector::make),
             py::arg("dictionary"),
             py::arg("width"),
             py::arg("height"),
             D(aruco_detector, make))


        ;
}
