/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(opencv_source.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(5d1ff548061dc3d26f88abf794311ce9)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/medusa/opencv_source.h>
// pydoc.h is automatically generated in the build directory
#include <opencv_source_pydoc.h>

void bind_opencv_source(py::module& m)
{

    using opencv_source = ::gr::medusa::opencv_source;


    py::class_<opencv_source,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<opencv_source>>(
        m, "opencv_source", D(opencv_source))

        .def(py::init(&opencv_source::make),
             py::arg("video_source"),
             py::arg("width"),
             py::arg("height"),
             D(opencv_source, make))


        ;
}
